version: '3.9'
services:
  streamlit_example:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_example
    ports:
      - '8501:8501'
    networks:
      - nginx_default
    restart: unless-stopped

networks:
  nginx_default:
    external: true

